### ISSUE TITLE
Where to download the kernel headers?

### ISSUE THREAD

**Issue by PjotrekSE** [sakaki-/bcm2711-kernel-bis#4]
Please excuse maybe a silly question:
Where can I download the corresponding kernel headers?

**Comment by sakaki-** [comment]
Hi,

So, I don't currently have the autobuild set up to create a corresponding header package each time, and I probably should >< On my todo list.

However, if you just want to build external programs against the kernel interfaces, then for most things the Gentoo package `sys-kernel/linux-headers-4.19`, which is [pre-installed](https://github.com/sakaki-/gentoo-on-rpi-64bit/blob/5e076709062a5048a68e549c4ffc1cc867a27b7b/reference/world-all-packages#L807) on my [gentoo-on-rpi-64bit](https://github.com/sakaki-/gentoo-on-rpi-64bit) image, will suffice. If you _aren't_ running Gentoo, you can still fetch the header binary package, and install them from that:
```console
# wget -c https://isshoni.org/pi64pie/sys-kernel/linux-headers-4.19.tbz2
```
This file is a [Gentoo XPAK](https://wiki.gentoo.org/wiki/Binary_package_guide#Understanding_the_binary_package_format), but can be unpacked like a regular `<...>.tar.bz2` file (the trailing extra metadata will be ignored), so:
```console
# tar -xjf linux-headers-4.19.tbz2 -C /
```
will install the headers from the package you just fetched, to `/usr/include/...`

If you want to build an out-of-tree module against the kernel, things are a little more involved. Please see e.g. [my notes here](https://www.raspberrypi.org/forums/viewtopic.php?p=1532808#p1532808) about building the `wireguard` module against one of these binary kernels.

hth, sakaki

**Comment by PjotrekSE** [comment]
Thank you very much.
