### ISSUE TITLE
This kernel runs 2 °C cooler than the std v8+ kernel

### ISSUE THREAD

**Issue by PjotrekSE** [sakaki-/bcm2711-kernel-bis#7]
The header says it all.
Since some time I run a service collecting CPU & GPU temperatures for my gatekeeper rpi 4B.
Used to be around 57 °C for the CPU and 1 °C less for the GPU with the standard  v8+ kernel.
After installing this kernel (4.19.83-v8-3c235dcfe80a-p4-bis+), it runs roughly 2 °C cooler, CPU 54.5 - 55.0 °C and GPU 54.0 - 55.0 °C.

**Comment by jfikar** [comment]
Anybody knows, what is the possible cause of the pleasant temperature decrease?
